apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: osdu-deployer-generic-test-za9gko
  namespace: default
spec:
  params:
  - name: namespace
    value: default
  - name: cpd-pipeline-name
    value: cloud-pak-deployer-5.0.x
  - name: access_key_id
    value: test
  - name: secret_access_key
    value: test
  - name: ansible_image
    value: 849574731431.dkr.ecr.us-east-1.amazonaws.com/ansible-installer:techzone-generic
  - name: partition_admin_password
    value: KQb49EqxpuXhNG-f
  - name: proj_name
    value: cpd
  - name: cpd_proj_name
    value: cpd-operators
  - name: router_certs
    value: letsencrypt-certs
  - name: tno_data
    value: "false"
  - name: block_storage
    value: ocs-storagecluster-ceph-rbd
  - name: file_storage
    value: ocs-storagecluster-cephfs
  - name: prereq_version
    value: "198"
  - name: osdu_version
    value: "279"
  - name: cpd_required
    value: "true"
  pipelineRef:
    name: osdu-deployer
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 12h0m0s
  workspaces:
  - name: source
    emptyDir: {}
