apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  labels:
    tekton.dev/pipeline: osdu-deployer
  generateName: osdu-deployer
  namespace: default
spec:
  params:
  - name: namespace
    value: default
  - name: cpd-pipeline-name
    value: cloud-pak-deployer-4.8.x-tse-l4-base
  - name: access_key_id
    value: himalay
  - name: secret_access_key
    value: himalay
  - name: ansible_image
    value: 849574731431.dkr.ecr.us-east-1.amazonaws.com/ansible-installer:techzone
  - name: partition_admin_password
    value: KQb49EqxpuXhNG-f
  - name: proj_name
    value: cpd
  - name: cpd_proj_name
    value: cpd-operators
  - name: router_certs
    value: letsencrypt-certs
  pipelineRef:
    name: osdu-deployer
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 8h0m0s
  workspaces:
  - name: source
    emptyDir: {}
